# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/bashe/Desktop/vita_projects/NESalizer-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/bashe/Desktop/vita_projects/NESalizer-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/bashe/Desktop/vita_projects/NESalizer-master/CMakeFiles /mnt/c/Users/bashe/Desktop/vita_projects/NESalizer-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/bashe/Desktop/vita_projects/NESalizer-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NESalizer.vpk

# Build rule for target.
NESalizer.vpk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NESalizer.vpk
.PHONY : NESalizer.vpk

# fast build rule for target.
NESalizer.vpk/fast:
	$(MAKE) -f CMakeFiles/NESalizer.vpk.dir/build.make CMakeFiles/NESalizer.vpk.dir/build
.PHONY : NESalizer.vpk/fast

#=============================================================================
# Target rules for targets named NESalizer.self

# Build rule for target.
NESalizer.self: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NESalizer.self
.PHONY : NESalizer.self

# fast build rule for target.
NESalizer.self/fast:
	$(MAKE) -f CMakeFiles/NESalizer.self.dir/build.make CMakeFiles/NESalizer.self.dir/build
.PHONY : NESalizer.self/fast

#=============================================================================
# Target rules for targets named NESalizer

# Build rule for target.
NESalizer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NESalizer
.PHONY : NESalizer

# fast build rule for target.
NESalizer/fast:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/build
.PHONY : NESalizer/fast

src/apu.obj: src/apu.cpp.obj

.PHONY : src/apu.obj

# target to build an object file
src/apu.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/apu.cpp.obj
.PHONY : src/apu.cpp.obj

src/apu.i: src/apu.cpp.i

.PHONY : src/apu.i

# target to preprocess a source file
src/apu.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/apu.cpp.i
.PHONY : src/apu.cpp.i

src/apu.s: src/apu.cpp.s

.PHONY : src/apu.s

# target to generate assembly for a file
src/apu.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/apu.cpp.s
.PHONY : src/apu.cpp.s

src/audio.obj: src/audio.cpp.obj

.PHONY : src/audio.obj

# target to build an object file
src/audio.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/audio.cpp.obj
.PHONY : src/audio.cpp.obj

src/audio.i: src/audio.cpp.i

.PHONY : src/audio.i

# target to preprocess a source file
src/audio.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/audio.cpp.i
.PHONY : src/audio.cpp.i

src/audio.s: src/audio.cpp.s

.PHONY : src/audio.s

# target to generate assembly for a file
src/audio.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/audio.cpp.s
.PHONY : src/audio.cpp.s

src/blip_buf.obj: src/blip_buf.cpp.obj

.PHONY : src/blip_buf.obj

# target to build an object file
src/blip_buf.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/blip_buf.cpp.obj
.PHONY : src/blip_buf.cpp.obj

src/blip_buf.i: src/blip_buf.cpp.i

.PHONY : src/blip_buf.i

# target to preprocess a source file
src/blip_buf.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/blip_buf.cpp.i
.PHONY : src/blip_buf.cpp.i

src/blip_buf.s: src/blip_buf.cpp.s

.PHONY : src/blip_buf.s

# target to generate assembly for a file
src/blip_buf.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/blip_buf.cpp.s
.PHONY : src/blip_buf.cpp.s

src/common.obj: src/common.cpp.obj

.PHONY : src/common.obj

# target to build an object file
src/common.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/common.cpp.obj
.PHONY : src/common.cpp.obj

src/common.i: src/common.cpp.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/controller.obj: src/controller.cpp.obj

.PHONY : src/controller.obj

# target to build an object file
src/controller.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/controller.cpp.obj
.PHONY : src/controller.cpp.obj

src/controller.i: src/controller.cpp.i

.PHONY : src/controller.i

# target to preprocess a source file
src/controller.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/controller.cpp.i
.PHONY : src/controller.cpp.i

src/controller.s: src/controller.cpp.s

.PHONY : src/controller.s

# target to generate assembly for a file
src/controller.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/controller.cpp.s
.PHONY : src/controller.cpp.s

src/cpu.obj: src/cpu.cpp.obj

.PHONY : src/cpu.obj

# target to build an object file
src/cpu.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/cpu.cpp.obj
.PHONY : src/cpu.cpp.obj

src/cpu.i: src/cpu.cpp.i

.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/cpu.cpp.i
.PHONY : src/cpu.cpp.i

src/cpu.s: src/cpu.cpp.s

.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/cpu.cpp.s
.PHONY : src/cpu.cpp.s

src/gui.obj: src/gui.cpp.obj

.PHONY : src/gui.obj

# target to build an object file
src/gui.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/gui.cpp.obj
.PHONY : src/gui.cpp.obj

src/gui.i: src/gui.cpp.i

.PHONY : src/gui.i

# target to preprocess a source file
src/gui.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/gui.cpp.i
.PHONY : src/gui.cpp.i

src/gui.s: src/gui.cpp.s

.PHONY : src/gui.s

# target to generate assembly for a file
src/gui.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/gui.cpp.s
.PHONY : src/gui.cpp.s

src/input.obj: src/input.cpp.obj

.PHONY : src/input.obj

# target to build an object file
src/input.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/input.cpp.obj
.PHONY : src/input.cpp.obj

src/input.i: src/input.cpp.i

.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s

.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/main.obj: src/main.cpp.obj

.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mapper.obj: src/mapper.cpp.obj

.PHONY : src/mapper.obj

# target to build an object file
src/mapper.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper.cpp.obj
.PHONY : src/mapper.cpp.obj

src/mapper.i: src/mapper.cpp.i

.PHONY : src/mapper.i

# target to preprocess a source file
src/mapper.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper.cpp.i
.PHONY : src/mapper.cpp.i

src/mapper.s: src/mapper.cpp.s

.PHONY : src/mapper.s

# target to generate assembly for a file
src/mapper.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper.cpp.s
.PHONY : src/mapper.cpp.s

src/mapper_0.obj: src/mapper_0.cpp.obj

.PHONY : src/mapper_0.obj

# target to build an object file
src/mapper_0.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_0.cpp.obj
.PHONY : src/mapper_0.cpp.obj

src/mapper_0.i: src/mapper_0.cpp.i

.PHONY : src/mapper_0.i

# target to preprocess a source file
src/mapper_0.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_0.cpp.i
.PHONY : src/mapper_0.cpp.i

src/mapper_0.s: src/mapper_0.cpp.s

.PHONY : src/mapper_0.s

# target to generate assembly for a file
src/mapper_0.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_0.cpp.s
.PHONY : src/mapper_0.cpp.s

src/mapper_1.obj: src/mapper_1.cpp.obj

.PHONY : src/mapper_1.obj

# target to build an object file
src/mapper_1.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_1.cpp.obj
.PHONY : src/mapper_1.cpp.obj

src/mapper_1.i: src/mapper_1.cpp.i

.PHONY : src/mapper_1.i

# target to preprocess a source file
src/mapper_1.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_1.cpp.i
.PHONY : src/mapper_1.cpp.i

src/mapper_1.s: src/mapper_1.cpp.s

.PHONY : src/mapper_1.s

# target to generate assembly for a file
src/mapper_1.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_1.cpp.s
.PHONY : src/mapper_1.cpp.s

src/mapper_10.obj: src/mapper_10.cpp.obj

.PHONY : src/mapper_10.obj

# target to build an object file
src/mapper_10.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_10.cpp.obj
.PHONY : src/mapper_10.cpp.obj

src/mapper_10.i: src/mapper_10.cpp.i

.PHONY : src/mapper_10.i

# target to preprocess a source file
src/mapper_10.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_10.cpp.i
.PHONY : src/mapper_10.cpp.i

src/mapper_10.s: src/mapper_10.cpp.s

.PHONY : src/mapper_10.s

# target to generate assembly for a file
src/mapper_10.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_10.cpp.s
.PHONY : src/mapper_10.cpp.s

src/mapper_11.obj: src/mapper_11.cpp.obj

.PHONY : src/mapper_11.obj

# target to build an object file
src/mapper_11.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_11.cpp.obj
.PHONY : src/mapper_11.cpp.obj

src/mapper_11.i: src/mapper_11.cpp.i

.PHONY : src/mapper_11.i

# target to preprocess a source file
src/mapper_11.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_11.cpp.i
.PHONY : src/mapper_11.cpp.i

src/mapper_11.s: src/mapper_11.cpp.s

.PHONY : src/mapper_11.s

# target to generate assembly for a file
src/mapper_11.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_11.cpp.s
.PHONY : src/mapper_11.cpp.s

src/mapper_13.obj: src/mapper_13.cpp.obj

.PHONY : src/mapper_13.obj

# target to build an object file
src/mapper_13.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_13.cpp.obj
.PHONY : src/mapper_13.cpp.obj

src/mapper_13.i: src/mapper_13.cpp.i

.PHONY : src/mapper_13.i

# target to preprocess a source file
src/mapper_13.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_13.cpp.i
.PHONY : src/mapper_13.cpp.i

src/mapper_13.s: src/mapper_13.cpp.s

.PHONY : src/mapper_13.s

# target to generate assembly for a file
src/mapper_13.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_13.cpp.s
.PHONY : src/mapper_13.cpp.s

src/mapper_2.obj: src/mapper_2.cpp.obj

.PHONY : src/mapper_2.obj

# target to build an object file
src/mapper_2.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_2.cpp.obj
.PHONY : src/mapper_2.cpp.obj

src/mapper_2.i: src/mapper_2.cpp.i

.PHONY : src/mapper_2.i

# target to preprocess a source file
src/mapper_2.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_2.cpp.i
.PHONY : src/mapper_2.cpp.i

src/mapper_2.s: src/mapper_2.cpp.s

.PHONY : src/mapper_2.s

# target to generate assembly for a file
src/mapper_2.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_2.cpp.s
.PHONY : src/mapper_2.cpp.s

src/mapper_232.obj: src/mapper_232.cpp.obj

.PHONY : src/mapper_232.obj

# target to build an object file
src/mapper_232.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_232.cpp.obj
.PHONY : src/mapper_232.cpp.obj

src/mapper_232.i: src/mapper_232.cpp.i

.PHONY : src/mapper_232.i

# target to preprocess a source file
src/mapper_232.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_232.cpp.i
.PHONY : src/mapper_232.cpp.i

src/mapper_232.s: src/mapper_232.cpp.s

.PHONY : src/mapper_232.s

# target to generate assembly for a file
src/mapper_232.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_232.cpp.s
.PHONY : src/mapper_232.cpp.s

src/mapper_28.obj: src/mapper_28.cpp.obj

.PHONY : src/mapper_28.obj

# target to build an object file
src/mapper_28.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_28.cpp.obj
.PHONY : src/mapper_28.cpp.obj

src/mapper_28.i: src/mapper_28.cpp.i

.PHONY : src/mapper_28.i

# target to preprocess a source file
src/mapper_28.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_28.cpp.i
.PHONY : src/mapper_28.cpp.i

src/mapper_28.s: src/mapper_28.cpp.s

.PHONY : src/mapper_28.s

# target to generate assembly for a file
src/mapper_28.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_28.cpp.s
.PHONY : src/mapper_28.cpp.s

src/mapper_3.obj: src/mapper_3.cpp.obj

.PHONY : src/mapper_3.obj

# target to build an object file
src/mapper_3.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_3.cpp.obj
.PHONY : src/mapper_3.cpp.obj

src/mapper_3.i: src/mapper_3.cpp.i

.PHONY : src/mapper_3.i

# target to preprocess a source file
src/mapper_3.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_3.cpp.i
.PHONY : src/mapper_3.cpp.i

src/mapper_3.s: src/mapper_3.cpp.s

.PHONY : src/mapper_3.s

# target to generate assembly for a file
src/mapper_3.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_3.cpp.s
.PHONY : src/mapper_3.cpp.s

src/mapper_4.obj: src/mapper_4.cpp.obj

.PHONY : src/mapper_4.obj

# target to build an object file
src/mapper_4.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_4.cpp.obj
.PHONY : src/mapper_4.cpp.obj

src/mapper_4.i: src/mapper_4.cpp.i

.PHONY : src/mapper_4.i

# target to preprocess a source file
src/mapper_4.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_4.cpp.i
.PHONY : src/mapper_4.cpp.i

src/mapper_4.s: src/mapper_4.cpp.s

.PHONY : src/mapper_4.s

# target to generate assembly for a file
src/mapper_4.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_4.cpp.s
.PHONY : src/mapper_4.cpp.s

src/mapper_5.obj: src/mapper_5.cpp.obj

.PHONY : src/mapper_5.obj

# target to build an object file
src/mapper_5.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_5.cpp.obj
.PHONY : src/mapper_5.cpp.obj

src/mapper_5.i: src/mapper_5.cpp.i

.PHONY : src/mapper_5.i

# target to preprocess a source file
src/mapper_5.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_5.cpp.i
.PHONY : src/mapper_5.cpp.i

src/mapper_5.s: src/mapper_5.cpp.s

.PHONY : src/mapper_5.s

# target to generate assembly for a file
src/mapper_5.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_5.cpp.s
.PHONY : src/mapper_5.cpp.s

src/mapper_7.obj: src/mapper_7.cpp.obj

.PHONY : src/mapper_7.obj

# target to build an object file
src/mapper_7.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_7.cpp.obj
.PHONY : src/mapper_7.cpp.obj

src/mapper_7.i: src/mapper_7.cpp.i

.PHONY : src/mapper_7.i

# target to preprocess a source file
src/mapper_7.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_7.cpp.i
.PHONY : src/mapper_7.cpp.i

src/mapper_7.s: src/mapper_7.cpp.s

.PHONY : src/mapper_7.s

# target to generate assembly for a file
src/mapper_7.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_7.cpp.s
.PHONY : src/mapper_7.cpp.s

src/mapper_71.obj: src/mapper_71.cpp.obj

.PHONY : src/mapper_71.obj

# target to build an object file
src/mapper_71.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_71.cpp.obj
.PHONY : src/mapper_71.cpp.obj

src/mapper_71.i: src/mapper_71.cpp.i

.PHONY : src/mapper_71.i

# target to preprocess a source file
src/mapper_71.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_71.cpp.i
.PHONY : src/mapper_71.cpp.i

src/mapper_71.s: src/mapper_71.cpp.s

.PHONY : src/mapper_71.s

# target to generate assembly for a file
src/mapper_71.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_71.cpp.s
.PHONY : src/mapper_71.cpp.s

src/mapper_9.obj: src/mapper_9.cpp.obj

.PHONY : src/mapper_9.obj

# target to build an object file
src/mapper_9.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_9.cpp.obj
.PHONY : src/mapper_9.cpp.obj

src/mapper_9.i: src/mapper_9.cpp.i

.PHONY : src/mapper_9.i

# target to preprocess a source file
src/mapper_9.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_9.cpp.i
.PHONY : src/mapper_9.cpp.i

src/mapper_9.s: src/mapper_9.cpp.s

.PHONY : src/mapper_9.s

# target to generate assembly for a file
src/mapper_9.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/mapper_9.cpp.s
.PHONY : src/mapper_9.cpp.s

src/md5.obj: src/md5.cpp.obj

.PHONY : src/md5.obj

# target to build an object file
src/md5.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/md5.cpp.obj
.PHONY : src/md5.cpp.obj

src/md5.i: src/md5.cpp.i

.PHONY : src/md5.i

# target to preprocess a source file
src/md5.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/md5.cpp.i
.PHONY : src/md5.cpp.i

src/md5.s: src/md5.cpp.s

.PHONY : src/md5.s

# target to generate assembly for a file
src/md5.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/md5.cpp.s
.PHONY : src/md5.cpp.s

src/menu.obj: src/menu.cpp.obj

.PHONY : src/menu.obj

# target to build an object file
src/menu.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/menu.cpp.obj
.PHONY : src/menu.cpp.obj

src/menu.i: src/menu.cpp.i

.PHONY : src/menu.i

# target to preprocess a source file
src/menu.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/menu.cpp.i
.PHONY : src/menu.cpp.i

src/menu.s: src/menu.cpp.s

.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/menu.cpp.s
.PHONY : src/menu.cpp.s

src/ppu.obj: src/ppu.cpp.obj

.PHONY : src/ppu.obj

# target to build an object file
src/ppu.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/ppu.cpp.obj
.PHONY : src/ppu.cpp.obj

src/ppu.i: src/ppu.cpp.i

.PHONY : src/ppu.i

# target to preprocess a source file
src/ppu.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/ppu.cpp.i
.PHONY : src/ppu.cpp.i

src/ppu.s: src/ppu.cpp.s

.PHONY : src/ppu.s

# target to generate assembly for a file
src/ppu.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/ppu.cpp.s
.PHONY : src/ppu.cpp.s

src/rom.obj: src/rom.cpp.obj

.PHONY : src/rom.obj

# target to build an object file
src/rom.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/rom.cpp.obj
.PHONY : src/rom.cpp.obj

src/rom.i: src/rom.cpp.i

.PHONY : src/rom.i

# target to preprocess a source file
src/rom.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/rom.cpp.i
.PHONY : src/rom.cpp.i

src/rom.s: src/rom.cpp.s

.PHONY : src/rom.s

# target to generate assembly for a file
src/rom.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/rom.cpp.s
.PHONY : src/rom.cpp.s

src/save_states.obj: src/save_states.cpp.obj

.PHONY : src/save_states.obj

# target to build an object file
src/save_states.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/save_states.cpp.obj
.PHONY : src/save_states.cpp.obj

src/save_states.i: src/save_states.cpp.i

.PHONY : src/save_states.i

# target to preprocess a source file
src/save_states.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/save_states.cpp.i
.PHONY : src/save_states.cpp.i

src/save_states.s: src/save_states.cpp.s

.PHONY : src/save_states.s

# target to generate assembly for a file
src/save_states.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/save_states.cpp.s
.PHONY : src/save_states.cpp.s

src/sdl_backend.obj: src/sdl_backend.cpp.obj

.PHONY : src/sdl_backend.obj

# target to build an object file
src/sdl_backend.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/sdl_backend.cpp.obj
.PHONY : src/sdl_backend.cpp.obj

src/sdl_backend.i: src/sdl_backend.cpp.i

.PHONY : src/sdl_backend.i

# target to preprocess a source file
src/sdl_backend.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/sdl_backend.cpp.i
.PHONY : src/sdl_backend.cpp.i

src/sdl_backend.s: src/sdl_backend.cpp.s

.PHONY : src/sdl_backend.s

# target to generate assembly for a file
src/sdl_backend.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/sdl_backend.cpp.s
.PHONY : src/sdl_backend.cpp.s

src/tables.obj: src/tables.c.obj

.PHONY : src/tables.obj

# target to build an object file
src/tables.c.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/tables.c.obj
.PHONY : src/tables.c.obj

src/tables.i: src/tables.c.i

.PHONY : src/tables.i

# target to preprocess a source file
src/tables.c.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/tables.c.i
.PHONY : src/tables.c.i

src/tables.s: src/tables.c.s

.PHONY : src/tables.s

# target to generate assembly for a file
src/tables.c.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/tables.c.s
.PHONY : src/tables.c.s

src/timing.obj: src/timing.cpp.obj

.PHONY : src/timing.obj

# target to build an object file
src/timing.cpp.obj:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/timing.cpp.obj
.PHONY : src/timing.cpp.obj

src/timing.i: src/timing.cpp.i

.PHONY : src/timing.i

# target to preprocess a source file
src/timing.cpp.i:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/timing.cpp.i
.PHONY : src/timing.cpp.i

src/timing.s: src/timing.cpp.s

.PHONY : src/timing.s

# target to generate assembly for a file
src/timing.cpp.s:
	$(MAKE) -f CMakeFiles/NESalizer.dir/build.make CMakeFiles/NESalizer.dir/src/timing.cpp.s
.PHONY : src/timing.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... NESalizer.vpk"
	@echo "... NESalizer.self"
	@echo "... NESalizer"
	@echo "... src/apu.obj"
	@echo "... src/apu.i"
	@echo "... src/apu.s"
	@echo "... src/audio.obj"
	@echo "... src/audio.i"
	@echo "... src/audio.s"
	@echo "... src/blip_buf.obj"
	@echo "... src/blip_buf.i"
	@echo "... src/blip_buf.s"
	@echo "... src/common.obj"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/controller.obj"
	@echo "... src/controller.i"
	@echo "... src/controller.s"
	@echo "... src/cpu.obj"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/gui.obj"
	@echo "... src/gui.i"
	@echo "... src/gui.s"
	@echo "... src/input.obj"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mapper.obj"
	@echo "... src/mapper.i"
	@echo "... src/mapper.s"
	@echo "... src/mapper_0.obj"
	@echo "... src/mapper_0.i"
	@echo "... src/mapper_0.s"
	@echo "... src/mapper_1.obj"
	@echo "... src/mapper_1.i"
	@echo "... src/mapper_1.s"
	@echo "... src/mapper_10.obj"
	@echo "... src/mapper_10.i"
	@echo "... src/mapper_10.s"
	@echo "... src/mapper_11.obj"
	@echo "... src/mapper_11.i"
	@echo "... src/mapper_11.s"
	@echo "... src/mapper_13.obj"
	@echo "... src/mapper_13.i"
	@echo "... src/mapper_13.s"
	@echo "... src/mapper_2.obj"
	@echo "... src/mapper_2.i"
	@echo "... src/mapper_2.s"
	@echo "... src/mapper_232.obj"
	@echo "... src/mapper_232.i"
	@echo "... src/mapper_232.s"
	@echo "... src/mapper_28.obj"
	@echo "... src/mapper_28.i"
	@echo "... src/mapper_28.s"
	@echo "... src/mapper_3.obj"
	@echo "... src/mapper_3.i"
	@echo "... src/mapper_3.s"
	@echo "... src/mapper_4.obj"
	@echo "... src/mapper_4.i"
	@echo "... src/mapper_4.s"
	@echo "... src/mapper_5.obj"
	@echo "... src/mapper_5.i"
	@echo "... src/mapper_5.s"
	@echo "... src/mapper_7.obj"
	@echo "... src/mapper_7.i"
	@echo "... src/mapper_7.s"
	@echo "... src/mapper_71.obj"
	@echo "... src/mapper_71.i"
	@echo "... src/mapper_71.s"
	@echo "... src/mapper_9.obj"
	@echo "... src/mapper_9.i"
	@echo "... src/mapper_9.s"
	@echo "... src/md5.obj"
	@echo "... src/md5.i"
	@echo "... src/md5.s"
	@echo "... src/menu.obj"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
	@echo "... src/ppu.obj"
	@echo "... src/ppu.i"
	@echo "... src/ppu.s"
	@echo "... src/rom.obj"
	@echo "... src/rom.i"
	@echo "... src/rom.s"
	@echo "... src/save_states.obj"
	@echo "... src/save_states.i"
	@echo "... src/save_states.s"
	@echo "... src/sdl_backend.obj"
	@echo "... src/sdl_backend.i"
	@echo "... src/sdl_backend.s"
	@echo "... src/tables.obj"
	@echo "... src/tables.i"
	@echo "... src/tables.s"
	@echo "... src/timing.obj"
	@echo "... src/timing.i"
	@echo "... src/timing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

